language: python
cache: pip
python:
  - 3.7
sudo: required
dist: xenail
notifications:
  email:
    recipients:
    - chris+manowar@halbersma.us
  on_success: always
  on_failure: always
before_script:
- "./travis/pre_build.sh"
- export DEBIAN_FRONTEND=noninteractive; sudo -E apt-get -y  install python3-pip python-dev
  shellcheck mariadb-server mariadb-client jq openjdk-8-jre graphviz openssh-server
- "./travis/ssh_setup.sh"
- "./travis/db_setup.sh"
- sudo pip3 install --upgrade setuptools
- sudo pip3 install -r requirements.txt
- sudo pip3 install mkdocs bandit
- gem install mdl
script:
- "./travis/testing.sh"
- "./travis/swagger_test.sh"
- "./travis/api_test.sh"
- "./travis/sapi_test.sh"
- "./travis/schedule_test.sh"
- "./travis/analyze_test.sh"
after_success:
- "./travis/build_diag.sh"
- "./travis/swagger_build.sh"
- "./travis/build_docs.sh"
- "./travis/packages.sh"
before_install:
- pwd
- openssl aes-256-cbc -K $encrypted_1acdf71f7d2b_key -iv $encrypted_1acdf71f7d2b_iv
  -in /home/travis/build/chalbersma/manowar/travis-manowar.enc -out /home/travis/build/chalbersma/manowar/travis-manowar -d
- chmod 600 /home/travis/build/chalbersma/manowar/travis-manowar
- eval `ssh-agent -s`
- ssh-add /home/travis/build/chalbersma/manowar/travis-manowar
