language: python
sudo: required
notifications:
  email:
    recipients:
    - chris+manowar@halbersma.us
  on_success: always
  on_failure: always
before_script:
- sudo apt-get -y install openssh-server
- "./travis/pre_build.sh"
- export DEBIAN_FRONTEND=noninteractive; sudo -E apt-get -y  install python3-pip python-dev shellcheck mariadb-server mariadb-client jq openjdk-7-jre graphviz
- "./travis/db_setup.sh"
- sudo pip3 install --upgrade setuptools
- sudo pip3 install -r requirements.txt
script:
- "./travis/testing.sh"
after_success:
- echo "build_process"
before_install:
- echo "future stuff here"
