language: python
sudo: required
notifications:
  email:
    recipients:
    - chris+manowar@halbersma.us
  on_success: always
  on_failure: always
before_script:
- sudo apt-get -y install openssh-server
- "./travis/pre_build.sh"
- "./travis/ssh_setup.sh"
- export DEBIAN_FRONTEND=noninteractive; sudo -E apt-get -y  install python3-pip python-dev
  shellcheck mariadb-server mariadb-client jq openjdk-7-jre graphviz
- "./travis/db_setup.sh"
- sudo pip3 install --upgrade setuptools
- sudo pip3 install bandit pylint paramiko pymysql colorama flask flask_cors jsonschema
  feedparser lxml pika mkdocs requests
- gem install mdl
script:
- "./travis/testing.sh"
- "./travis/swagger_test.sh"
- "./travis/api_test.sh"
- "./travis/sapi_test.sh"
- "./travis/schedule_test.sh"
- "./travis/analyze_test.sh"
- "./travis/build_diag.sh"
after_success:
- "./travis/swagger_build.sh"
- "./travis/build_docs.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_1acdf71f7d2b_key -iv $encrypted_1acdf71f7d2b_iv
  -in travis-manowar.enc -out /home/chalbersma/tmp/travis-manowar/travis-manowar -d
