@startuml

package "jellyfishaudits" {
	[bassaudits]
	[staticaudits]
}

package "analyze.py" {
	[analyze]
	[generic_large_compare]
	[subtype_large_compare]
	[generic_large_analysis_store]
}

database "jellyfish2" {
	[collections]
	[hosts]
	[audits]
	[audits_by_host]
}

[analyze] ---> [bassaudits] : Uses
[analyze] ---> [staticaudits] : Uses
[analyze] ---> [audits] : Stores or Updates Audits
[analyze] <--> [hosts] : grab_host_list()
[analyze] <--> [generic_large_compare] : Check for Passing And Failure
[analyze] <--> [subtype_large_compare] : Check for Passing And Failure
[generic_large_compare] ---> [collections] : Uses
[subtype_large_compare] ---> [collections] : Uses
[generic_large_compare] ---> [generic_large_analysis_store] : Sends Results
[subtype_large_compare] ---> [generic_large_analysis_store] : Sends Results
[generic_large_analysis_store] ---> [audits_by_host] : Stores Results


@enduml
