@startuml

' Diagram that describes how the collate moduel works.

package "collate.py" {
	[grab_all_table_data]
	[grab_multiple_collated]
	[grab_single_collated]
	[compare_update_insert_table]
	[get_current_table_data]
}

database "jellyfish2" {
	[audits_by_host]
	[audits_by_pop]
	[audits_by_srvtype]
	[audits_by_acoll]
}

' Program Flow

[grab_all_table_data] <--- [grab_multiple_collated] : Data Request
[grab_multiple_collated] ---> [grab_single_collated] : Uses

[grab_all_table_data] <--- [get_current_table_data] : Data Request

[grab_all_table_data] ---> [compare_update_insert_table] : Uses

' Database Relationships

[grab_single_collated] ---> [audits_by_host] : Select

[get_current_table_data] ---> [audits_by_pop] : Select
[get_current_table_data] ---> [audits_by_srvtype] : Select
[get_current_table_data] ---> [audits_by_acoll] : Select

[compare_update_insert_table] ---> [audits_by_pop] : Insert/Update
[compare_update_insert_table] ---> [audits_by_srvtype] : Insert/Update
[compare_update_insert_table] ---> [audits_by_acoll] : Insert/Update



@enduml
