@startuml

cloud AWS {
	database "rds:jellyfish2" {
		rectangle collections
		rectangle hosts
	}
	rectangle jellyfish_api
}

cloud Command_and_Control {
	node scheduler_box
}

cloud Network {
	node stingcell_target
	node nonstingcell_target
}

scheduler_box ---> jellyfish_api : Push
scheduler_box <---> nonstingcell_target : Pull

stingcell_target ---> jellyfish_api : Push

jellyfish_api ---> collections : Insert/Update
jellyfish_api ---> hosts : Insert/Update


@enduml
