#! /bin/sh
### BEGIN INIT INFO
# Provides: jellyfish2-ui
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 3 5
# Default-Stop: 0 1 6
# Short-Description: jellyfish2-ui
# Description: This file starts and stops Jellyfish2's Flask Server
# 
### END INIT INFO

# Set Me
J2Loc_dir=/jellyfish
USER=jellyfish
SHELL=/bin/bash

case "$1" in
 start)
   su ${USER} -s ${SHELL} -c "${J2Loc_dir}/run_ui.sh"
   ;;
 stop)
   su ${USER} -s ${SHELL} -c "${J2Loc_dir}/stop_ui.sh"
   sleep 2
   ;;
 restart)
   su ${USER} -s ${SHELL} -c "${J2Loc_dir}/stop_ui.sh"
   sleep 3 
   su ${USER} -s ${SHELL} -c "${J2Loc_dir}/run_ui.sh"
   ;;
 status)
   su ${USER} -s ${SHELL} -c "${J2Loc_dir}/status_ui.sh"
   ;;
 *)
   echo "Usage: jellyfish2-ui {start|stop|restart|status}" >&2
   exit 3
   ;;
esac
